### ISSUE TITLE
Not working in 52.1

### ISSUE THREAD

**Issue by rowild** [3raxton/ForeignIpsum#17]
Just found your plugin - thank you! looks really nice!

Unfortunately I couldn't get it to work in Sketch 52.1. 

What I did:
- Hit "T" to insert text layer
- Go to plugin, choose English

What I expect:
Text layer is filled with lorem ispum text

What really happens
nothing

**Comment by 3raxton** [comment]
Hey @rowild glad you find Foreign Ipsum helpful and opened an issue! 

I just tried it on Sketch 52.1 and 52.2, and I can't seem to duplicate the issue. Did you make sure to select the text layer before running the plugin? Just want to make sure any possible workflow kinks are worked out before diving deeper. 

If you did, could you share a demonstration of the issue here or reach out to me by email (braxtonhuff[dot]us[at]gmail[dot]com)? 

Cheers!

**Comment by rowild** [comment]
Wow! You respond quickly!!! Great!

I just found my workflow hickup: I need to deactivate the text that is created when drawing a text field with "T". After that I focused another layer, then activated the newly created text layer and used the plugin on it. Now it works. Sorry for the confusion! 

But maybe it would be worth a hint in the Readme for those, who don't use Sketch on a daily basis. :-)

Thanks again!

**Comment by 3raxton** [comment]
Just happened to be up at the time & thought I’d respond. I need to add some type of notification telling the user the plugin ran and give a few more details in the README for cases like this. 

I’m sure you’re not the only one and I’m glad you brought it up! 

Let me know if you have any more questions and I’ll be happy to help out. Maybe I’ll make a static site for the plugin this weekend in order to give straightforward instructions for the plugin. 

Thanks again & cheers!

**Comment by rowild** [comment]
Any chance I could convince you to keep the instructions in the readme instead of a static site? We all work with many little things thrown together from many different resources. Any click that reduces the learning curve is most welcome. Also, when there are many resources, each and every update requires all the resources to be updated, too. This might be additional work for you. And quite often we find ourselves finding outdated, but still highly ranked sources on google. Therefore I am an advocate for "one resource for as much info as possible".

Thanks for your offer! At them moment I have no question! Your plugin works great, and the different languages are a lot of fun! I find myself wasting some time here ... ;-)

**Comment by 3raxton** [comment]
I'm convinced; your request makes perfect sense. I agree with you that it is easier not to search for instructions and rather have them at the forefront of something like the README file. One resource for as much information as possible it is. 

Glad to hear it is working well for you and helps with the workflow. Have you found it to populate layers with too much text or do you have any suggestions? 

Thanks again for the feedback, cheers!

**Comment by rowild** [comment]
Great!!!

About the text length: I found myself in various situations, where once there was too much text, then the right amount, and on other places too little. So this is a matter that is very much dependent on the current situation. For me that is fine! Any- and everything is better then writing stupid "dblablabladfl kdjfgoiejrt kjydfhjp" stuff for blind texts :-)

Are you thinking about making it more configurable? Like VS Code's "Faker" (which I like very much)?

**Comment by 3raxton** [comment]
That's what I was afraid of, and I'm kind of leaving it for the users to gauge it based on what they need. I wish I could reach out to more users and ask about the use case, but it seems like it works fine this way as well. How many sentences did you end up using in your text layer? 

Rather than something similar to faker, I would like to give the plugin a UI where users can pick from a dropdown of languages rather than going to the plugin menu. Adding a number of sentences option would be nice as well, but I need to get the UI down first. 

I'll happily take any suggestions you have! 💯
